# Creo il file CloudFormation base

AWSTemplateFormatVersion: '2010-09-09'
Description: SageMaker Pipeline Infrastructure

Resources:
  # S3 Bucket per i dati
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub sagemaker-pipeline-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled

  # Ruolo IAM per SageMaker
  SageMakerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  # SageMaker Pipeline
  ModelPipeline:
    Type: AWS::SageMaker::Pipeline
    Properties:
      PipelineName: !Sub ${ProjectName}-pipeline
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      PipelineDefinition:
        PipelineDefinitionBody: !Sub |
          {
            "Version": "2020-12-01",
            "Parameters": [],
            "Steps": []
          }

  Outputs: null
  DataBucketName:
    Description: Nome del bucket S3 per i dati
    Value: !Ref DataBucket

  SageMakerRoleArn:
    Description: ARN del ruolo IAM per SageMaker
    Value: !GetAtt SageMakerExecutionRole.Arn

  PipelineName:
    Description: Nome della pipeline SageMaker
    Value: !Ref ModelPipeline

# AWSTemplateFormatVersion: '2010-09-09'
# Description: 'MLOps Pipeline with SageMaker'

# Parameters:
#   ProjectName:
#     Type: String
#     Default: mlops-pipeline
#     Description: Nome del progetto

#   ModelName:
#     Type: String
#     Default: ml-model
#     Description: Nome del modello

# Resources:
#   # S3 Bucket per i dati
#   DataBucket:
#     Type: AWS::S3::Bucket
#     Properties:
#       BucketName: !Sub ${ProjectName}-data-${AWS::AccountId}
#       VersioningConfiguration:
#         Status: Enabled

#   # Ruolo IAM per SageMaker
#   SageMakerExecutionRole:
#     Type: AWS::IAM::Role
#     Properties:
#       AssumeRolePolicyDocument:
#         Version: '2012-10-17'
#         Statement:
#           - Effect: Allow
#             Principal:
#               Service: sagemaker.amazonaws.com
#             Action: sts:AssumeRole
#       ManagedPolicyArns:
#         - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
#         - arn:aws:iam::aws:policy/AmazonS3FullAccess

#   # SageMaker Pipeline
#   ModelPipeline:
#     Type: AWS::SageMaker::Pipeline
#     Properties:
#       PipelineName: !Sub ${ProjectName}-pipeline
#       RoleArn: !GetAtt SageMakerExecutionRole.Arn
#       PipelineDefinition:
#         PipelineDefinitionBody: !Sub |
#           {
#             "Version": "2020-12-01",
#             "Parameters": [],
#             "Steps": []
#           }

# Outputs:
#   DataBucketName:
#     Description: Nome del bucket S3 per i dati
#     Value: !Ref DataBucket

#   SageMakerRoleArn:
#     Description: ARN del ruolo IAM per SageMaker
#     Value: !GetAtt SageMakerExecutionRole.Arn

#   PipelineName:
#     Description: Nome della pipeline SageMaker
#     Value: !Ref ModelPipeline